---
title: "Methodology"
---

# Our Protocol

The curves presented on the site are derived from modelling scenarios that have impacted public policies implemented in France. They were mainly produced by the Pasteur Institute and Inserm. As the data are not available in free access, we have extracted them from the report curves using [WebPlotDigitilizer](https://automeris.io/WebPlotDigitizer/).

To allow for a proper evaluation of the modelling scenarios, only those scenarios with verified assumptions were retained, including the hypotheses regarding the restrictive measures implemented. In order not to introduce bias (e.g., taking only those scenarios that overestimated reality, or the opposite), we studied all the reports. We analysed:

1. all the models from the Pasteur Institute reports, published on their [web page](https://modelisation-covid19.pasteur.fr/)
2. the models quoted in the [Scientific Council reports](https://solidarites-sante.gouv.fr/actualites/presse/dossiers-de-presse/article/conseil-scientifique-covid-19), which led us to identify Inserm scenarios for January-February 2021
3. the [Imperial College modelling for the 1st lockdown](https://www.imperial.ac.uk/mrc-global-infectious-disease-analysis/covid-19/report-12-global-impact-covid-19/), cited by the Scientific Council which had a major impact on French public policies
4. a retrospective google search with delimited dates for each month and the keywords "INSERM", "Pasteur", "modeling", "scenario". This allowed to identify scenarios not officially published but nevertheless cited by the press: [Pasteur Institute for the 2nd lockdown](https://www.lesechos.fr/economie-france/social/covid-la-decrue-dans-les-services-de-reanimation-esperee-en-france-dans-une-dizaine-de-jours-1261656)of November 2020, and Pasteur Institute for the [lockdown exit of the Ile-de-France in May 2020.](https://www.lesechos.fr/idees-debats/editos-analyses/pourquoi-philippe-a-douche-les-francais-1199309)

Finally, we focus on hospital indicators, and exclude the number of cases from our analysis. We believe that there are two reasons for this exclusion. The first is that the number of cases is a less objective indicator than the number of occupied beds, because it depends in particular on the propensity of the French to be tested, which varies over time. Secondly, the number of cases does not say much about the danger of infections. From January 2022 onwards, the number of cases is 10 times higher than the pre-Omicron figures, without a proportional impact on the hospital.

# Comprehensive list of reports

The complete list of modelling scenarios, and whether or not they were included in the site analysis (with the justification) is available below, along with links to the reports in question.

<details>

<summary style="cursor: pointer; padding: 3px;">

**Institut Pasteur Modelling** *(click to unfold)*

</summary>

-   [April 29, 2020](https://www.lesechos.fr/idees-debats/editos-analyses/pourquoi-philippe-a-douche-les-francais-1199309) : included (not officially published but transcribed by the press)
-   [September 25, 2020](https://www.sdbio.eu/images/acymailing/Simulations%20Institut%20Pasteur%2025%2009%202020.pdf) : excluded (restricitve measures were taken in September, so the scenarios are no longer comparable with reality)
-   [Octobre 30, 2020](https://www.lesechos.fr/economie-france/social/covid-la-decrue-dans-les-services-de-reanimation-esperee-en-france-dans-une-dizaine-de-jours-1261656) : included (these are the models of the 2nd lockdown, not published on the Institut Pasteur website but transcribed by the press)
-   [February 8, 2021](https://modelisation-covid19.pasteur.fr/variant/RapportInstitutPasteur_variants_8fevrier2021.pdf) : included
-   [February 23, 2021](https://hal-pasteur.archives-ouvertes.fr/pasteur-03149525) : included
-   [March 29, 2021](https://www.eurosurveillance.org/content/10.2807/1560-7917.ES.2021.26.9.2100133) : no scenarios in the report
-   [April 6, 2021](https://www.thelancet.com/journals/eclinm/article/PIIS2589-5370(21)00281-9/fulltext) : excluded (the curves presented are a counterfactual of the epidemic evolution in the absence of vaccination)
-   [April 26, 2021](https://modelisation-covid19.pasteur.fr/loosening/Scenarios_de_levee_des_mesures_de_freinage_20210426.pdf) : included
-   [May 21, 2021](https://modelisation-covid19.pasteur.fr/loosening/Mise_a_jour_scenarios_de_levee_des_mesures_de_freinage_20210521.pdf) : included. We did not need to analyze ourselves, the comparison being already carried out in an informal way on twitter by Simon Cauchemez in charge of the modeling team of the Institut Pasteur
-   [July 9, 2021](https://modelisation-covid19.pasteur.fr/variant/Institut_Pasteur_dynamique_du_variant_Delta_en_France_metropolitaine_20210709.pdf) : excluded (the implementation of the sanitary pass was not included in the modeling assumptions, so the scenarios are no longer comparable with reality)
-   [July 26, 2021](https://modelisation-covid19.pasteur.fr/variant/Institut_Pasteur_Acceleration_vaccination_et_Delta_20210726.pdf) : included (the scenarios take into account the implementation of the sanitary pass)
-   [August 5, 2021](https://modelisation-covid19.pasteur.fr/variant/InstitutPasteur_Dynamiques_regionales_des_hospitalisations_20210805.pdf) : included (the scenarios take into account the implementation of the sanitary pass)
-   [September 6, 2021](https://hal-pasteur.archives-ouvertes.fr/pasteur-03272638v2) : no scenarios in the report
-   [October 4, 2021](https://modelisation-covid19.pasteur.fr/scenarios/InstitutPasteur_scenariosCOVID19AutomneHiver_2021.pdf) : included
-   [November 29, 2021](https://modelisation-covid19.pasteur.fr/scenarios/Institut_Pasteur_diminution_de_limmunit%C3%A9_et_rappel_20211129.pdf) : excluded (impact of the Omicron variant 2 weeks later, which was not included in the models). We were still able to compare short-term projections during the short 2-week window before the Omicron variant distorted the results.
-   [December 2, 2021](https://modelisation-covid19.pasteur.fr/scenarios/Institut_Pasteur_Complement_rapport_rappel_20211202.pdf) : excluded (impact of the Omicron variant 2 weeks later, which was not included in the models). We were still able to compare short-term projections during the short 2-week window before the Omicron variant distorted the results.
-   [Decemeber 27, 2021](https://modelisation-covid19.pasteur.fr/variant/Institut_Pasteur_Impact_dOmicron_sur_lepidemie_francaise_20211227.pdf) : included through the report of January 7. Indeed, it is specified that "given the uncertainties [...], it is not possible to quantify precisely the impact that the Omicron wave will have". About a hundred scenarios were then produced. The following report of January 7, which we have analyzed, uses this report as a basis, after excluding the scenarios that do not fit the properties of Omicron.
-   [January 7, 2022](https://modelisation-covid19.pasteur.fr/variant/InstitutPasteur_Complement_Analyse_Impact_Omicron_20220107_corrige.pdf) : included
-   [February 15, 2022](https://modelisation-covid19.pasteur.fr/variant/Institut_Pasteur_Comparaison_Observations_projections_Omicron_20220215.pdf) : this report does not produce a scenario but a retrospective on the previous report of January 7. We discuss this in our analysis of the latter report.
-   [February 21, 2022](https://modelisation-covid19.pasteur.fr/variant/Institut_Pasteur_Impact_BA_2_epidemie_francaise_20220221.pdf) : excluded. Focuses only on the number of cases, which is an exclusionary criterion in our methodology as explained above.
-   [March 10, 2022](https://modelisation-covid19.pasteur.fr/variant/InstitutPasteur_impact_BA2_relachement_mesures_20220310.pdf) : excluded. Focuses only on the number of cases, which is an exclusionary criterion in our methodology as explained above.

</details>

<details>

<summary style="cursor: pointer; padding: 3px;">

**INSERM Modelling**  *(click to unfold)*

</summary>

-   January-February 2021 models: included because they appear in the [report of the Scientific Council of January 29, 2021](https://solidarites-sante.gouv.fr/IMG/pdf/note_eclairage_variants_modelisation_29_janvier_2021.pdf) suggesting the establishment of a strict confinement. They have also been published in the press. These models appeared in the Inserm reports of [January 16, 2021](https://www.epicx-lab.com/uploads/9/6/9/4/9694133/inserm_covid-19-voc_dominance-20210116.pdf), [February 2, 2021](https://www.epicx-lab.com/uploads/9/6/9/4/9694133/inserm-covid-19-voc-lockdown-20210202.pdf) and [February 14, 2021](https://www.epicx-lab.com/uploads/9/6/9/4/9694133/inserm_covid-19-voc_socialdistancing-20210214.pdf).

</details>

<details>

<summary style="cursor: pointer; padding: 3px;">

**Imperial College Modelling**  *(click to unfold)*

</summary>

-   [modelling of report 12](https://www.imperial.ac.uk/mrc-global-infectious-disease-analysis/covid-19/report-12-global-impact-covid-19/), and in particular its [appendix](https://www.imperial.ac.uk/media/imperial-college/medicine/mrc-gida/Imperial-College-COVID19-Global-unmitigated-mitigated-suppression-scenarios.xlsx): included as a major argument in favor of lockdown in the [report of the Scientific Council of March 12, 2020](https://solidarites-sante.gouv.fr/IMG/pdf/avis_conseil_scientifique_12_mars_2020.pdf). It has also been cited by many media as having been a decisive argument in favor of lockdown, e.g. in [Le Monde](https://www.lemonde.fr/planete/article/2020/03/15/coronavirus-les-simulations-alarmantes-des-epidemiologistes-pour-la-france_6033149_3244.html) or in [Libération](https://www.liberation.fr/evenements-libe/2020/03/16/l-urgence-eviter-la-saturation-des-services-de-sante_1781988/)

</details>
